FROM ghcr.io/inblockio/aqua-docker-mediawiki:fix-login-issue
#FROM inblockio/micro-pkc-mediawiki:1.0.0-alpha.5
WORKDIR /var/www/html
RUN mkdir ./extensions/DataAccounting
COPY . ./extensions/DataAccounting/
